FROM python:3.10-slim

## Top level args / env vars
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive

## Install gh
RUN apt-get update -y \
    && apt-get -y install \
    curl \
    && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt update \
    && apt install gh -y

## Apt based dependencies
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get -y install \
    curl \
    build-essential \
    gh \
    git \
    jq \
    vim \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

## Create unpriv user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

ENV PROJ_ROOT=/opt/using_guidance
RUN mkdir -p ${PROJ_ROOT}/using_guidance && chown $USERNAME -R /opt/
USER ${USERNAME}
WORKDIR ${PROJ_ROOT}
RUN python3 -m pip install --user pdm
RUN python3 -m pdm self update
COPY --chown=${USERNAME} pyproject.toml pdm.lock README.md ${PROJ_ROOT}
RUN python3 -m pdm install --no-self -G :all

## Install oh my zsh
# Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions

# ## Add default entrypoint
COPY .docker/entrypoint.sh /
RUN sudo chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

USER root
RUN echo "source /entrypoint.sh" >> /etc/profile
USER $USERNAME
